name: Linting

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
    

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      - name: Run clang-format
        run: clang-format source/*.cpp --dry-run -Werror

      - name: Run cppcheck
        run: cppcheck ./source

